### ISSUE TITLE
[10.0.1xx-rc2] AspNetCore Build Failure due to Analyzer Compiler Version Mismatch

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#5345]
[Link to failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2800035&view=logs&j=f8361ec4-8613-5f7f-2f10-d7dd7654e93f&t=db03af06-1031-5cdf-2daa-050507a710e7&l=1191)

AspNetCore is failing to build in the public and internal 10.0 RC2 branches due to a compiler version mismatch. The error encountered is:

```
CSC : error CS9057: Analyzer assembly '/__w/1/s/src/aspnetcore/artifacts/bin/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Release/netstandard2.0/Microsoft.AspNetCore.Http.RequestDelegateGenerator.dll' cannot be used because it references version '5.1.0.0' of the compiler, which is newer than the currently running version '5.0.0.0'. [/__w/1/s/src/aspnetcore/src/Identity/Core/src/Microsoft.AspNetCore.Identity.csproj]
```

**Comment by mthalman** [comment]
I don't know if the warning is the cause of the failure. I see this error as well:

`  CSC : error CS9057: Analyzer assembly '/__w/1/s/src/aspnetcore/artifacts/bin/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Release/netstandard2.0/Microsoft.AspNetCore.Http.RequestDelegateGenerator.dll' cannot be used because it references version '5.1.0.0' of the compiler, which is newer than the currently running version '5.0.0.0'. [/__w/1/s/src/aspnetcore/src/Identity/Core/src/Microsoft.AspNetCore.Identity.csproj]
`

**Comment by MichaelSimons** [comment]
The aspnetcore.log indicates the following error:

```
CSC : error CS9057: Analyzer assembly '/__w/1/s/src/aspnetcore/artifacts/bin/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Release/netstandard2.0/Microsoft.AspNetCore.Http.RequestDelegateGenerator.dll' cannot be used because it references version '5.1.0.0' of the compiler, which is newer than the currently running version '5.0.0.0'. [/__w/1/s/src/aspnetcore/src/Identity/Core/src/Microsoft.AspNetCore.Identity.csproj]
    0 Warning(s)
    1 Error(s)
```

That smells like a bootstrapping issue - we do not allow re-bootstrapping once we are in RC mode.  @wtgodbe

**Comment by wtgodbe** [comment]
This is due to an incorrect flow from Roslyn main, bumping the version there to 5.1. https://github.com/dotnet/dotnet/pull/2598 should fix
