### ISSUE TITLE
Alpine317_Offline_MsftSdk_x64 leg is failing due to unknown type name 'off64_t'

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4339]
`8.0.1xx` build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2432961&view=logs&j=2c0e385a-a18f-5b69-6454-703331eaa440&t=cf76e2d0-96be-511a-8062-c67cc03c82cb

Working build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2432836&view=logs&j=2c0e385a-a18f-5b69-6454-703331eaa440&t=cf76e2d0-96be-511a-8062-c67cc03c82cb

The Alpine leg is failing due to unknown type name 'off64_t', error message:

      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/debug/createdump/crashinfounix.cpp:519:49: error: unknown type name 'off64_t'; did you mean 'off_t'?
        519 |         *read = pread64(m_fdMem, buffer, size, (off64_t)address);
            |                                                 ^~~~~~~
            |                                                 off_t
      /usr/include/bits/alltypes.h:162:16: note: 'off_t' declared here
        162 | typedef _Int64 off_t;
            |                ^
      /vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/debug/createdump/crashinfounix.cpp:519:17: error: use of undeclared identifier 'pread64'
        519 |         *read = pread64(m_fdMem, buffer, size, (off64_t)address);
            |                 ^
      2 errors generated.
    ##[error]Failed to build "CoreCLR component".

**Comment by NikolaMilosavljevic** [comment]
@jkoritzinsky

**Comment by NikolaMilosavljevic** [comment]
@dotnet/dotnet-coreclr-admin

**Comment by MichaelSimons** [comment]
This is a blocker for May servicing.

**Comment by jkoritzinsky** [comment]
The Alpine 3.17 leg that is failing is running on Alpine 3.19. Is that intentional?

It looks like we have a fix in main for this, I'm investigating it now.

**Comment by MichaelSimons** [comment]
> The Alpine 3.17 leg that is failing is running on Alpine 3.19. Is that intentional?
That was an oversight introduced in https://github.com/dotnet/installer/pull/19318/.  I will fix the name.

**Comment by richlander** [comment]
Just so I understand, what would have happened if we hadn't made this change? Do we expect that the Alpine community would have been hit by this? I'm guessing that there is nothing special about this servicing release, other than the PR we merged. Does that suggest that no one in the Alpine community is doing this same thing?

**Comment by jkoritzinsky** [comment]
The problem is that musl libc removed the `off64_t` typedef, so anyone trying to build .NET 8 on Alpine 3.19 would be broken. This wasn't a problem before because the pipeline was validating that we could build on Alpine 3.17, which was before the typedef was removed.

**Comment by richlander** [comment]
Thanks for the explanation.

**Comment by jkoritzinsky** [comment]
Fixed by dotnet/installer#19544
