### ISSUE TITLE
Razor-compiler System.Memeory build issues caused by package downgrade

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3005]
When performing a bootstrap build in 7.0-rc1, everyplace that references Microsoft.CodeAnalysis.CSharp in razor-compiler encounters the following errors.  

```
error NU1605: Detected package downgrade: System.Memory from 4.5.5 to 4.5.4. Reference the package directly from the project to select a different version.  [/repos/tarball-rc1/src/razor-compiler/artifacts/source-build/self/src/razor-compiler.sln]
error NU1605:  Microsoft.CodeAnalysis.Razor -> Microsoft.CodeAnalysis.CSharp 4.4.0 -> Microsoft.CodeAnalysis.Common 4.4.0 -> System.Collections.Immutable 7.0.0-rc.1.22422.23 -> System.Memory (>= 4.5.5)  [/repos/tarball-rc1/src/razor-compiler/artifacts/source-build/self/src/razor-compiler.sln]
error NU1605:  Microsoft.CodeAnalysis.Razor -> Microsoft.CodeAnalysis.CSharp 4.4.0 -> Microsoft.CodeAnalysis.Common 4.4.0 -> System.Memory (>= 4.5.4) [/repos/tarball-rc1/src/razor-compiler/artifacts/source-build/self/src/razor-compiler.sln]
```

Accepting the downgrade via `nowarn` NU1605 causes the following compiler errors:

```
    CSC : error CS1705: Assembly 'System.Collections.Immutable' with identity 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Memory' with identity 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(117,25): error CS0019: Operator '!=' cannot be applied to operands of type 'method group' and 'method group' [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(122,37): error CS0019: Operator '<' cannot be applied to operands of type 'int' and 'method group' [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(193,26): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'tagHelpersFromCompilation'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(193,53): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'tagHelpersFromReferences'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(194,33): error CS0019: Operator '+' cannot be applied to operands of type 'method group' and 'method group' [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(213,28): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'sourceItem'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(213,40): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'imports'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(213,50): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'allTagHelpers'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(213,66): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'razorSourceGeneratorOptions'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(241,22): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'hintName'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(241,32): error CS8130: Cannot infer the type of implicitly-typed deconstruction variable 'csharpDocument'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(104,50): error CS8821: A static anonymous function cannot contain a reference to 'this' or 'base'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(172,50): error CS8821: A static anonymous function cannot contain a reference to 'this' or 'base'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(218,36): error CS8821: A static anonymous function cannot contain a reference to 'this' or 'base'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
    /tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs(220,41): error CS8821: A static anonymous function cannot contain a reference to 'this' or 'base'. [/tarball/src/razor-compiler/artifacts/source-build/self/src/src/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj]
```

This issue can be resolved by adding an explicit System.Memory Version 4.5.5 reference everyplace Microsoft.CodeAnalysis.CSharp is referenced.  It feels like the better fix however is to push this version upgrade into Microsoft.CodeAnalysis.CSharp which is where the version conflict originates.

**Comment by MichaelSimons** [comment]
This was resolved in https://github.com/dotnet/installer/pull/14384
