### ISSUE TITLE
AzureLinux verticals are failing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4866]
```
    /__w/1/s/src/runtime/src/coreclr/pal/src/thread/process.cpp:2572:16: error: use of undeclared identifier 'MEMBARRIER_CMD_PRIVATE_EXPEDITED'
       2572 |         mask & MEMBARRIER_CMD_PRIVATE_EXPEDITED)
            |                ^
      [ 85%] Building CXX object pal/src/CMakeFiles/coreclrpal.dir/arch/amd64/signalhandlerhelper.cpp.o
      /__w/1/s/src/runtime/src/coreclr/pal/src/thread/process.cpp:2575:24: error: use of undeclared identifier 'MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED'
       2575 |         if (membarrier(MEMBARRIER_CMD_REGISTER_PRIVATE_EXPEDITED, 0, 0) == 0)
            |                        ^
      [ 85%] Built target eventing_headers
      /__w/1/s/src/runtime/src/coreclr/pal/src/thread/process.cpp:2640:33: error: use of undeclared identifier 'MEMBARRIER_CMD_PRIVATE_EXPEDITED'
       2640 |         int status = membarrier(MEMBARRIER_CMD_PRIVATE_EXPEDITED, 0, 0);
            |                                 ^
      3 errors generated.
      make[3]: *** [pal/src/CMakeFiles/coreclrpal.dir/build.make:944: pal/src/CMakeFiles/coreclrpal.dir/thread/process.cpp.o] Error 1
      make[3]: *** Waiting for unfinished jobs....

```

Maybe regressed with https://github.com/dotnet/sdk/commit/affada6e1e99189c71777602c6764b1e8d61b8b1?

**Comment by ViktorHofer** [comment]
cc @jkotas (https://github.com/dotnet/runtime/pull/111943)

**Comment by jkotas** [comment]
Should this be fixed in dotnet/sdk or dotnet/dotnet?

**Comment by ViktorHofer** [comment]
dotnet/sdk
